name: Run Dependabot on PR
on:
  pull_request:
    branches:
      - main
jobs:
  dependabot-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Dependabot
        uses: dependabot/dependabot-core@main
        with:
          directory: "/"
          package-ecosystem: "devcontainers"
          target-branch: "main"
